import { MenuItem, Testimonial, GalleryItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // --- SIGNATURE DRINKS ---
  {
    id: 'sig-zellco-creme',
    name: 'Zellco Creme de la Creme',
    category: 'specialty',
    price: 48000,
    description: 'Espresso excelsa racikan rumah dipadu susu gandum premium, sirup karamel bakar artisanal, dan diselimuti vanilla cheese foam lembut dengan taburan garam laut Bali.',
    tastingNotes: ['Burnt Caramel', 'Vanilla Cream', 'Salted Chocolate'],
    intensity: 4,
    acidity: 'Low',
    origin: 'House Blend (Kerinci & Gayo)',
    imageUrl: 'https://images.unsplash.com/photo-1572442388796-11668a67e53f?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: false,
    isIceAvailable: true,
  },
  {
    id: 'sig-smoked-sea-salt',
    name: 'Smoked Sea Salt Seaweed Latte',
    category: 'specialty',
    price: 46000,
    description: 'Sensasi unik dari espresso dingin yang disiram sirup rum kelapa organik, dihiasi sea salt-infused cream, dan taburan nori panggang khas Zellco.',
    tastingNotes: ['Coconut', 'Woody Smoke', 'Savory Sweet'],
    intensity: 3,
    acidity: 'Low',
    origin: 'Flores Bajawa Solok',
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: false,
    isIceAvailable: true,
  },
  {
    id: 'sig-lavender-haze',
    name: 'Lavender Haze Cold Brew',
    category: 'specialty',
    price: 45000,
    description: 'Sajian cold brew murni hasil ekstraksi 18 jam, dipadukan sirup lavender alami buatan dapur kami, perasan lemon segar, dan air soda berkarbonasi.',
    tastingNotes: ['Floral Lavender', 'Bright Lemon', 'Blackberry'],
    intensity: 2,
    acidity: 'High',
    origin: 'Ethiopian Sidama Micro-lot',
    imageUrl: 'https://images.unsplash.com/photo-1513530534585-c7b1394c6d51?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: false,
    isIceAvailable: true,
  },

  // --- ESPRESSO BASED ---
  {
    id: 'esp-piccolo',
    name: 'Specialist Piccolo Latte',
    category: 'espresso',
    price: 38000,
    description: 'Ristretto pekat ganda dengan susu panas bertekstur beludru mikro, disajikan dalam gelas kaca kecil 90ml untuk kepekatan aroma cokelat murni.',
    tastingNotes: ['Dark Chocolate', 'Toasted Almond', 'Creamy Milk'],
    intensity: 5,
    acidity: 'Low',
    origin: 'Zellco Golden Blend (Columbia & Gayo)',
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: true,
    isIceAvailable: false,
  },
  {
    id: 'esp-islay-espresso',
    name: 'Spiced Flat White',
    category: 'espresso',
    price: 40000,
    description: 'Dual shot espresso berbasis biji kopi Flores Bajawa dengan susu evaporasi berempah pala saksama dan kayu manis organik Sumatra.',
    tastingNotes: ['Nutmeg', 'Cinnamon Spice', 'Brown Sugar'],
    intensity: 4,
    acidity: 'Low',
    origin: 'Single Origin Flores Bajawa',
    imageUrl: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: true,
    isIceAvailable: true,
  },
  {
    id: 'esp-vanilla-shakerato',
    name: 'Espresso Shakerato Double Peak',
    category: 'espresso',
    price: 39000,
    description: 'Espresso ganda yang dikocok cepat bersama es batu, gula aren cair lokal, dan sejumput ekstrak biji vanilla asli Madagaskar hingga menghasilkan busa dingin berlimpah.',
    tastingNotes: ['Bold Espresso', 'Warm Vanilla', 'Caramelized Sugar'],
    intensity: 4,
    acidity: 'Medium',
    origin: 'Java Preanger Semeru',
    imageUrl: 'https://images.unsplash.com/photo-1497515114629-f71d768fd07c?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: false,
    isIceAvailable: true,
  },

  // --- MANUAL BREW ---
  {
    id: 'man-geisha-v60',
    name: 'Panama Geisha Esmeralda (V60)',
    category: 'manual',
    price: 120000,
    description: 'Biji legendaris Panama Geisha yang diseduh presisi dengan suhu air 91°C menggunakan dripper Hario V60 tetsuya. Membuka kompleksitas buah yang ajaib.',
    tastingNotes: ['Bergamot Jasmine', 'Peach Nectar', 'Earl Grey Tea'],
    intensity: 2,
    acidity: 'High',
    origin: 'Hacienda La Esmeralda, Panama',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: true,
    isIceAvailable: true,
  },
  {
    id: 'man-ethiopia-yirg',
    name: 'Ethiopia Yirgacheffe Kochere (Kalita Wave)',
    category: 'manual',
    price: 48000,
    description: 'Menggunakan Dripper Kalita Wave berdasar rata untuk ekstraksi manis yang seimbang. Menghasilkan rasa teh herbal buah-buahan tropis yang manis bercahaya.',
    tastingNotes: ['Blueberry', 'Lemon Zest', 'Honey Sweetness'],
    intensity: 2,
    acidity: 'High',
    origin: 'Kochere Region, Ethiopia',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: true,
    isIceAvailable: true,
  },
  {
    id: 'man-gayo-wine',
    name: 'Aceh Gayo Wine Process (Syphon)',
    category: 'manual',
    price: 52000,
    description: 'Proses fermentasi ceri kopi anaerobik selama 30 hari menghasilkan cita rasa menyerupai anggur merah beralkohol (namun 100% bebas alkohol), diseduh dengan metode Syphon uap.',
    tastingNotes: ['Red Wine Aroma', 'Fermented Berry', 'Dark Cocoa Finish'],
    intensity: 4,
    acidity: 'Medium',
    origin: 'Central Gayo Highlands, 1500 masl',
    imageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: true,
    isIceAvailable: false,
  },

  // --- PASTRY ---
  {
    id: 'pas-pistachio-babka',
    name: 'Artisan Pistachio Rose Babka',
    category: 'pastry',
    price: 36000,
    description: 'Roti ragi kepang berlapis pasta kacang pistachio gurih manis, ditaburi kelopak mawar kering organik yang harum semerbak.',
    tastingNotes: ['Butter Rich', 'Roasted Pistachio', 'Delicate Rose aroma'],
    intensity: 1,
    acidity: 'None',
    origin: 'Zellco Bakery House',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: true,
    isIceAvailable: false,
  },
  {
    id: 'pas-butter-croissant',
    name: 'Double-Fold Butter Croissant',
    category: 'pastry',
    price: 28000,
    description: 'Croissant khas Perancis klasik yang dinobatkan terbaik di kota kami. Memiliki 81 lapisan renyah karamel di luar dan sangat lembut serta kaya mentega Prancis di dalam.',
    tastingNotes: ['Rich French Butter', 'Crispy Golden Layer'],
    intensity: 1,
    acidity: 'None',
    origin: 'Zellco Bakery House',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: true,
    isIceAvailable: false,
  },
  {
    id: 'pas-truffle-quiche',
    name: 'Wild Mushroom & Truffle Quiche',
    category: 'pastry',
    price: 49000,
    description: 'Adonan pie renyah berisikan custard telur lembut penuh dengan jamur hutan liar portobello, bayam organik, dan disiram minyak truffle putih murni.',
    tastingNotes: ['Earthy Truffle', 'Umami Mushroom', 'Savory Flaky Crust'],
    intensity: 2,
    acidity: 'None',
    origin: 'Zellco Cuisine Collab',
    imageUrl: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&w=600&q=80',
    isHotAvailable: true,
    isIceAvailable: false,
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'rev-1',
    author: 'Renata Laksmana',
    role: 'Coffee Enthusias & Q-Grader',
    rating: 5,
    reviewText: 'Zellco Coffee telah membawa standar manual brew di kota ini ke level tertinggi. Panama Geisha yang diseduh menggunakan Hario V60 di sini memiliki simplisitas bergamot yang sangat jernih dan manis yang tak tertandingi.',
    favoriteDrink: 'Panama Geisha Esmeralda (V60)',
    date: '10 Mei 2026',
  },
  {
    id: 'rev-2',
    author: 'Bagas Aditya',
    role: 'Arsitek & Digital Nomad',
    rating: 5,
    reviewText: 'Dari sekian banyak kafe, Zellco paling memikirkan kebutuhan pencahayaan dan akustiknya. Sangat kondusif untuk bekerja, sambil menikmati segelas Zellco Creme de la Creme yang super gurih gurih manis!',
    favoriteDrink: 'Zellco Creme de la Creme',
    date: '18 Mei 2026',
  },
  {
    id: 'rev-3',
    author: 'Nabila Syakieb',
    role: 'Editor Gaya Hidup',
    rating: 5,
    reviewText: 'Lokasinya terselubung dengan interior minimal-nordik yang berkelas tinggi. Detail penyajiannya sangat estetik, sangat merekomendasikan Spiced Flat White yang harum jahe pala serta Croissant mentega berlapisnya.',
    favoriteDrink: 'Spiced Flat White & Butter Croissant',
    date: '21 Mei 2026',
  }
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'The Slow Bar Sanctuary',
    description: 'Area seduh intim berhiaskan batu marmer abu-abu gelap, tempat barista kami berinteraksi dan meracik kopi manual brew pesanan khusus.',
    imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1000&q=80',
    category: 'slowbar',
  },
  {
    id: 'gal-2',
    title: 'Nordic Sunlit Study',
    description: 'Ruang dalam didesain minimalis dengan kombinasi kayu jati alami dan beton ekspos, ideal untuk fokus bekerja atau tenggelam dalam bacaan hangat.',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1000&q=80',
    category: 'indoor',
  },
  {
    id: 'gal-3',
    title: 'The Green Glasshouse',
    description: 'Teras luar berkonsep kebun kaca hijau, rimbun dengan tanaman monstera dan pakis liar, terasa sejuk alami sepanjang hari.',
    imageUrl: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1000&q=80',
    category: 'outdoor',
  },
  {
    id: 'gal-4',
    title: 'La Marzocco Craft Chamber',
    description: 'Pusat stasiun espresso kami dipersenjatai mesin legendaris La Marzocco KB90 berlapis krom baja tahan karat.',
    imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1000&q=80',
    category: 'slowbar',
  }
];
